name: CI (Debug)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore FishstrapV2.sln

    - name: Build
      run: dotnet build FishstrapV2.sln --no-restore

    - name: Publish
      run: dotnet publish -p:PublishSingleFile=true -r win-x64 -c Debug --self-contained false .\FishstrapV2\FishstrapV2.csproj

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        path: .\FishstrapV2\bin\Debug\net8.0-windows\win-x64\publish\FishstrapV2.exe
        archive: false
